name: sql
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - comm=0.1.4
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - ipykernel=6.26.0
  - ipython=8.18.0
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - openssl=3.0.12
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.0.0
  - prompt-toolkit=3.0.41
  - prompt_toolkit=3.0.41
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.11.5
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pyzmq=25.1.0
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.13.0
  - typing_extensions=4.8.0
  - wcwidth=0.2.12
  - wheel=0.41.2
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - attrs==23.1.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - fastjsonschema==2.19.0
      - fonttools==4.45.1
      - greenlet==3.0.1
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.1
      - kiwisolver==1.4.5
      - matplotlib==3.8.2
      - nbformat==5.9.2
      - numpy==1.26.2
      - pandas==2.1.3
      - pillow==10.1.0
      - plotly==5.18.0
      - psycopg2-binary==2.9.9
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - referencing==0.31.0
      - rpds-py==0.13.1
      - seaborn==0.13.0
      - sqlalchemy==2.0.23
      - tenacity==8.2.3
      - tzdata==2023.3
